apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvn-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvn-app
  template:
    metadata:
      labels:
        app: mvn-app
    spec:
      containers:
        - name: mvn-app
          image: houwayda/devops_esprit:32
          imagePullPolicy: Always
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: mvn-app
spec:
  type: NodePort
  selector:
    app: mvn-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31005
